"""
Django settings for nubrain project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


APP_NAME = 'NuBrain'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u^nsuu%javcin$i#yn1%ef-+j^xxxh7)_ue5-u0=1-j0iv6rgp'

# Application definition

INSTALLED_APPS = (
    'django_admin_bootstrapped',
    'bootstrap3',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'brain',  # our magic goes here...
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'nubrain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nubrain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '%s-db.sqlite3' % APP_NAME),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


# - LOGGING ---------------
import errno
from dateutil.easter import datetime
import logging


def make_sure_path_exists(path):
    try:
        os.makedirs(path)
    except OSError as exception:
        if exception.errno != errno.EEXIST:
            raise

LOG_DIR = "%s/logs" % BASE_DIR
make_sure_path_exists(LOG_DIR)
MAIN_LOG = '%s/log_%s' % (LOG_DIR,
                          datetime.date.strftime(datetime.date.today(), '%b_%d_%Y'))
LOG_LEVEL = logging.ERROR
# END LOGGING ---------------

MEDIA_ROOT = '%s/media/' % BASE_DIR
STATIC_ROOT = '%s/static/' % BASE_DIR

BASE_URL = ''
DEBUG = False
TEMPLATE_DEBUG = DEBUG
ALLOWED_HOSTS = []
APPEND_SLASH = True

# ---- APP STUFF ---------
APP_META = {
    'NAME': APP_NAME,
    'DESCRIPTION': 'transcend - leverage a nu brain!',
    'AUTHOR': 'NuChwezi'
}


# Django-Admin-Bootstrapped
DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'
from django.contrib import messages
MESSAGE_TAGS = {
    messages.SUCCESS: 'alert-success success',
    messages.WARNING: 'alert-warning warning',
    messages.ERROR: 'alert-danger error'
}

from settings_local import *
# DON'T move stuff below this line (to above this line), unless u know
# what's happening...

LOGIN_URL = '%sadmin/login/' % BASE_URL
LOGOUT_URL = '%sadmin/logout/' % BASE_URL
MEDIA_URL = '%s/media/' % BASE_URL
STATIC_URL = '%s/static/' % BASE_URL


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors':
            ("django.contrib.auth.context_processors.auth",
             "django.template.context_processors.debug",
             "django.template.context_processors.i18n",
             "django.template.context_processors.media",
             "django.template.context_processors.static",
             "django.template.context_processors.tz",
             "django.contrib.messages.context_processors.messages"),
            'debug': TEMPLATE_DEBUG,
        },
        'DIRS': ['%s/%s/templates/' % (BASE_DIR, c) for c in ['nubrain', 'brain']]
    },
]
